export interface TarotCard {
  id: number
  name: string
  suit: 'major' | 'wands' | 'cups' | 'swords' | 'pentacles'
  number?: number
  meaning: string
  reversedMeaning: string
  description: string
  keywords: string[]
  image: string
}

export const tarotCards: TarotCard[] = [
  // Major Arcana
  {
    id: 0,
    name: 'The Fool',
    suit: 'major',
    meaning: 'New beginnings, innocence, spontaneity, free spirit',
    reversedMeaning: 'Recklessness, risk-taking, naivety',
    description: 'The Fool represents new beginnings and having faith in the future. He is stepping forward into the unknown, trusting that the universe will guide him.',
    keywords: ['new beginnings', 'innocence', 'adventure', 'freedom'],
    image: '🃏',
  },
  {
    id: 1,
    name: 'The Magician',
    suit: 'major',
    meaning: 'Manifestation, resourcefulness, power, inspired action',
    reversedMeaning: 'Manipulation, poor planning, untapped talents',
    description: 'The Magician represents the ability to manifest your desires through willpower and skill. He has all the tools he needs to succeed.',
    keywords: ['manifestation', 'power', 'skill', 'concentration'],
    image: '🎭',
  },
  {
    id: 2,
    name: 'The High Priestess',
    suit: 'major',
    meaning: 'Intuition, sacred knowledge, divine feminine, subconscious mind',
    reversedMeaning: 'Secrets, disconnected from intuition, withdrawal',
    description: 'The High Priestess represents intuition, mystery, and inner knowledge. She sits between the conscious and subconscious worlds.',
    keywords: ['intuition', 'mystery', 'subconscious', 'inner knowledge'],
    image: '🌙',
  },
  {
    id: 3,
    name: 'The Empress',
    suit: 'major',
    meaning: 'Femininity, beauty, nature, nurturing, abundance',
    reversedMeaning: 'Creative block, dependence on others, emptiness',
    description: 'The Empress represents abundance, nurturing, and the beauty of nature. She is the mother figure of the tarot.',
    keywords: ['abundance', 'nurturing', 'fertility', 'beauty'],
    image: '👑',
  },
  {
    id: 4,
    name: 'The Emperor',
    suit: 'major',
    meaning: 'Authority, structure, control, fatherhood, leadership',
    reversedMeaning: 'Domination, excessive control, lack of discipline',
    description: 'The Emperor represents authority, structure, and control. He is the father figure of the tarot.',
    keywords: ['authority', 'structure', 'control', 'leadership'],
    image: '🏛️',
  },
  {
    id: 5,
    name: 'The Hierophant',
    suit: 'major',
    meaning: 'Spiritual wisdom, religious beliefs, conformity, tradition',
    reversedMeaning: 'Personal beliefs, freedom, challenging the status quo',
    description: 'The Hierophant represents spiritual wisdom and religious beliefs. He is the bridge between heaven and earth.',
    keywords: ['tradition', 'spirituality', 'conformity', 'beliefs'],
    image: '📿',
  },
  {
    id: 6,
    name: 'The Lovers',
    suit: 'major',
    meaning: 'Love, harmony, relationships, choices, alignment',
    reversedMeaning: 'Self-love, disharmony, imbalance, misalignment',
    description: 'The Lovers represent love, harmony, and relationships. They also represent choices and alignment of values.',
    keywords: ['love', 'harmony', 'relationships', 'choices'],
    image: '💕',
  },
  {
    id: 7,
    name: 'The Chariot',
    suit: 'major',
    meaning: 'Control, willpower, success, action, determination',
    reversedMeaning: 'Self-discipline, opposition, lack of direction',
    description: 'The Chariot represents control, willpower, and success. He moves forward with determination and focus.',
    keywords: ['control', 'willpower', 'success', 'determination'],
    image: '⚔️',
  },
  {
    id: 8,
    name: 'Strength',
    suit: 'major',
    meaning: 'Strength, courage, persuasion, influence, compassion',
    reversedMeaning: 'Inner strength, self-doubt, low energy, raw emotion',
    description: 'Strength represents courage, compassion, and inner strength. She tames the lion with love, not force.',
    keywords: ['strength', 'courage', 'patience', 'control'],
    image: '🦁',
  },
  {
    id: 9,
    name: 'The Hermit',
    suit: 'major',
    meaning: 'Soul-searching, introspection, being alone, inner guidance',
    reversedMeaning: 'Isolation, loneliness, withdrawal',
    description: 'The Hermit represents soul-searching and introspection. He seeks inner guidance and wisdom.',
    keywords: ['introspection', 'solitude', 'guidance', 'wisdom'],
    image: '🏔️',
  },
  {
    id: 10,
    name: 'Wheel of Fortune',
    suit: 'major',
    meaning: 'Good luck, karma, life cycles, destiny, turning point',
    reversedMeaning: 'Bad luck, resistance to change, breaking cycles',
    description: 'The Wheel of Fortune represents the cycles of life and destiny. What goes up must come down.',
    keywords: ['luck', 'karma', 'cycles', 'destiny'],
    image: '☸️',
  },
  {
    id: 11,
    name: 'Justice',
    suit: 'major',
    meaning: 'Justice, fairness, truth, cause and effect, law',
    reversedMeaning: 'Unfairness, lack of accountability, dishonesty',
    description: 'Justice represents fairness, truth, and the law of cause and effect. Every action has a consequence.',
    keywords: ['justice', 'fairness', 'truth', 'law'],
    image: '⚖️',
  },
  {
    id: 12,
    name: 'The Hanged Man',
    suit: 'major',
    meaning: 'Pause, surrender, letting go, new perspectives',
    reversedMeaning: 'Delays, resistance, stalling, indecision',
    description: 'The Hanged Man represents surrender and seeing things from a new perspective. Sometimes you must let go to move forward.',
    keywords: ['surrender', 'perspective', 'letting go', 'sacrifice'],
    image: '🙃',
  },
  {
    id: 13,
    name: 'Death',
    suit: 'major',
    meaning: 'Endings, change, transformation, transition',
    reversedMeaning: 'Resistance to change, personal transformation, inner purging',
    description: 'Death represents endings and transformation. It is not physical death, but the end of a cycle.',
    keywords: ['transformation', 'endings', 'change', 'transition'],
    image: '💀',
  },
  {
    id: 14,
    name: 'Temperance',
    suit: 'major',
    meaning: 'Balance, moderation, patience, purpose',
    reversedMeaning: 'Imbalance, excess, self-healing, re-alignment',
    description: 'Temperance represents balance, moderation, and patience. She blends opposites to create something new.',
    keywords: ['balance', 'moderation', 'patience', 'harmony'],
    image: '⚗️',
  },
  {
    id: 15,
    name: 'The Devil',
    suit: 'major',
    meaning: 'Shadow self, attachment, addiction, restriction',
    reversedMeaning: 'Releasing limiting beliefs, exploring dark thoughts, detachment',
    description: 'The Devil represents shadow self and attachment. He shows us what holds us back.',
    keywords: ['attachment', 'shadow', 'restriction', 'addiction'],
    image: '😈',
  },
  {
    id: 16,
    name: 'The Tower',
    suit: 'major',
    meaning: 'Sudden change, upheaval, chaos, revelation, awakening',
    reversedMeaning: 'Personal transformation, fear of change, averting disaster',
    description: 'The Tower represents sudden change and upheaval. Sometimes destruction is necessary for rebuilding.',
    keywords: ['upheaval', 'sudden change', 'revelation', 'awakening'],
    image: '🗼',
  },
  {
    id: 17,
    name: 'The Star',
    suit: 'major',
    meaning: 'Hope, faith, purpose, renewal, spirituality',
    reversedMeaning: 'Lack of faith, despair, self-trust, disconnection',
    description: 'The Star represents hope, faith, and renewal. She shines her light in the darkness.',
    keywords: ['hope', 'faith', 'renewal', 'inspiration'],
    image: '⭐',
  },
  {
    id: 18,
    name: 'The Moon',
    suit: 'major',
    meaning: 'Illusion, fear, anxiety, subconscious, intuition',
    reversedMeaning: 'Release of fear, repressed emotion, inner confusion',
    description: 'The Moon represents illusion and the subconscious. Things are not always as they seem.',
    keywords: ['illusion', 'intuition', 'subconscious', 'fear'],
    image: '🌕',
  },
  {
    id: 19,
    name: 'The Sun',
    suit: 'major',
    meaning: 'Positivity, fun, warmth, success, vitality',
    reversedMeaning: 'Inner child, feeling down, overly optimistic',
    description: 'The Sun represents positivity, joy, and success. It shines light on everything.',
    keywords: ['joy', 'success', 'positivity', 'vitality'],
    image: '☀️',
  },
  {
    id: 20,
    name: 'Judgement',
    suit: 'major',
    meaning: 'Judgement, rebirth, inner calling, absolution',
    reversedMeaning: 'Self-doubt, inner critic, ignoring the call',
    description: 'Judgement represents rebirth and inner calling. It is time to answer your higher purpose.',
    keywords: ['rebirth', 'calling', 'judgement', 'awakening'],
    image: '📯',
  },
  {
    id: 21,
    name: 'The World',
    suit: 'major',
    meaning: 'Completion, integration, accomplishment, travel',
    reversedMeaning: 'Seeking personal closure, short-cuts, delays',
    description: 'The World represents completion and accomplishment. You have reached the end of your journey.',
    keywords: ['completion', 'accomplishment', 'integration', 'wholeness'],
    image: '🌍',
  },
  // Wands
  {
    id: 22,
    name: 'Ace of Wands',
    suit: 'wands',
    number: 1,
    meaning: 'Inspiration, new opportunities, growth, potential',
    reversedMeaning: 'An emerging idea, lack of direction, distractions, delays',
    description: 'The Ace of Wands represents new inspiration and opportunities. A spark of creativity is about to ignite.',
    keywords: ['inspiration', 'opportunity', 'growth', 'potential'],
    image: '🔥',
  },
  {
    id: 23,
    name: 'Two of Wands',
    suit: 'wands',
    number: 2,
    meaning: 'Future planning, progress, decisions, discovery',
    reversedMeaning: 'Personal goals, inner alignment, fear of unknown',
    description: 'The Two of Wands represents planning and looking to the future. You have the world in your hands.',
    keywords: ['planning', 'progress', 'decisions', 'discovery'],
    image: '🌏',
  },
  {
    id: 24,
    name: 'Three of Wands',
    suit: 'wands',
    number: 3,
    meaning: 'Progress, expansion, foresight, overseas opportunities',
    reversedMeaning: 'Playing small, lack of foresight, unexpected delays',
    description: 'The Three of Wands represents expansion and looking beyond the horizon. Your ships are coming in.',
    keywords: ['expansion', 'progress', 'foresight', 'opportunity'],
    image: '🚢',
  },
  {
    id: 25,
    name: 'Four of Wands',
    suit: 'wands',
    number: 4,
    meaning: 'Celebration, harmony, marriage, home, community',
    reversedMeaning: 'Personal celebration, inner harmony, conflict with others',
    description: 'The Four of Wands represents celebration and harmony. It is a time of joy and community.',
    keywords: ['celebration', 'harmony', 'home', 'community'],
    image: '🎉',
  },
  {
    id: 26,
    name: 'Five of Wands',
    suit: 'wands',
    number: 5,
    meaning: 'Conflict, disagreements, competition, tension, diversity',
    reversedMeaning: 'Inner conflict, conflict avoidance, tension release',
    description: 'The Five of Wands represents conflict and competition. There is tension and disagreement.',
    keywords: ['conflict', 'competition', 'tension', 'disagreement'],
    image: '⚔️',
  },
  {
    id: 27,
    name: 'Six of Wands',
    suit: 'wands',
    number: 6,
    meaning: 'Success, public recognition, progress, self-confidence',
    reversedMeaning: 'Private achievement, personal pride, fear of failure',
    description: 'The Six of Wands represents success and public recognition. You are being celebrated for your achievements.',
    keywords: ['success', 'recognition', 'achievement', 'confidence'],
    image: '🏆',
  },
  {
    id: 28,
    name: 'Seven of Wands',
    suit: 'wands',
    number: 7,
    meaning: 'Challenge, competition, perseverance, protective',
    reversedMeaning: 'Exhaustion, giving up, overwhelmed',
    description: 'The Seven of Wands represents challenge and standing your ground. You must defend your position.',
    keywords: ['challenge', 'perseverance', 'defense', 'competition'],
    image: '🛡️',
  },
  {
    id: 29,
    name: 'Eight of Wands',
    suit: 'wands',
    number: 8,
    meaning: 'Movement, fast-paced change, action, alignment, air travel',
    reversedMeaning: 'Delays, frustration, resisting change, internal alignment',
    description: 'The Eight of Wands represents swift movement and change. Things are happening quickly.',
    keywords: ['movement', 'speed', 'action', 'change'],
    image: '💨',
  },
  {
    id: 30,
    name: 'Nine of Wands',
    suit: 'wands',
    number: 9,
    meaning: 'Resilience, courage, persistence, test of faith, boundaries',
    reversedMeaning: 'Inner resources, struggle, overwhelm, defensive',
    description: 'The Nine of Wands represents resilience and persistence. You are almost there, don\'t give up.',
    keywords: ['resilience', 'persistence', 'courage', 'boundaries'],
    image: '🧱',
  },
  {
    id: 31,
    name: 'Ten of Wands',
    suit: 'wands',
    number: 10,
    meaning: 'Burden, extra responsibility, hard work, completion',
    reversedMeaning: 'Doing it all, carrying the burden, delegation, release',
    description: 'The Ten of Wands represents burden and hard work. You are carrying too much on your shoulders.',
    keywords: ['burden', 'responsibility', 'hard work', 'completion'],
    image: '🏋️',
  },
  // Cups
  {
    id: 32,
    name: 'Ace of Cups',
    suit: 'cups',
    number: 1,
    meaning: 'Love, new feelings, emotional awakening, creativity',
    reversedMeaning: 'Self-love, intuition, repressed emotions',
    description: 'The Ace of Cups represents new emotional beginnings. Love and creativity are overflowing.',
    keywords: ['love', 'emotion', 'creativity', 'intuition'],
    image: '💧',
  },
  {
    id: 33,
    name: 'Two of Cups',
    suit: 'cups',
    number: 2,
    meaning: 'Unified love, partnership, mutual attraction, connection',
    reversedMeaning: 'Self-love, break-ups, disharmony, disconnection',
    description: 'The Two of Cups represents partnership and mutual attraction. Two souls are coming together.',
    keywords: ['partnership', 'love', 'connection', 'attraction'],
    image: '💑',
  },
  {
    id: 34,
    name: 'Three of Cups',
    suit: 'cups',
    number: 3,
    meaning: 'Celebration, friendship, creativity, collaborations',
    reversedMeaning: 'Independence, alone time, hardcore partying, three\'s a crowd',
    description: 'The Three of Cups represents celebration and friendship. It is a time of joy with friends.',
    keywords: ['celebration', 'friendship', 'joy', 'community'],
    image: '🥂',
  },
  {
    id: 35,
    name: 'Four of Cups',
    suit: 'cups',
    number: 4,
    meaning: 'Meditation, contemplation, apathy, reevaluation',
    reversedMeaning: 'Retreat, withdrawal, checking in for alignment',
    description: 'The Four of Cups represents meditation and contemplation. You are being offered something new.',
    keywords: ['meditation', 'contemplation', 'apathy', 'reevaluation'],
    image: '🧘',
  },
  {
    id: 36,
    name: 'Five of Cups',
    suit: 'cups',
    number: 5,
    meaning: 'Regret, failure, disappointment, pessimism, loss',
    reversedMeaning: 'Personal setbacks, self-forgiveness, moving on',
    description: 'The Five of Cups represents regret and disappointment. You are focused on what is lost.',
    keywords: ['regret', 'loss', 'disappointment', 'grief'],
    image: '😢',
  },
  {
    id: 37,
    name: 'Six of Cups',
    suit: 'cups',
    number: 6,
    meaning: 'Revisiting the past, childhood memories, innocence, joy',
    reversedMeaning: 'Living in the past, forgiveness, lacking playfulness',
    description: 'The Six of Cups represents nostalgia and childhood memories. The past is calling.',
    keywords: ['nostalgia', 'childhood', 'innocence', 'memories'],
    image: '🎠',
  },
  {
    id: 38,
    name: 'Seven of Cups',
    suit: 'cups',
    number: 7,
    meaning: 'Opportunities, choices, wishful thinking, illusion',
    reversedMeaning: 'Alignment, personal values, overwhelmed by choices',
    description: 'The Seven of Cups represents opportunities and choices. Not everything is as it seems.',
    keywords: ['choices', 'illusion', 'opportunities', 'dreams'],
    image: '☁️',
  },
  {
    id: 39,
    name: 'Eight of Cups',
    suit: 'cups',
    number: 8,
    meaning: 'Disappointment, abandonment, withdrawal, escapism',
    reversedMeaning: 'Trying one more time, indecision, aimless drifting',
    description: 'The Eight of Cups represents walking away from what no longer serves you.',
    keywords: ['abandonment', 'withdrawal', 'letting go', 'moving on'],
    image: '🚶',
  },
  {
    id: 40,
    name: 'Nine of Cups',
    suit: 'cups',
    number: 9,
    meaning: 'Contentment, satisfaction, gratitude, wish come true',
    reversedMeaning: 'Inner happiness, materialism, dissatisfaction',
    description: 'The Nine of Cups represents contentment and wishes coming true. Your dreams are manifesting.',
    keywords: ['contentment', 'satisfaction', 'gratitude', 'wishes'],
    image: '😊',
  },
  {
    id: 41,
    name: 'Ten of Cups',
    suit: 'cups',
    number: 10,
    meaning: 'Divine love, blissful relationships, harmony, alignment',
    reversedMeaning: 'Disconnection, misaligned values, struggling relationships',
    description: 'The Ten of Cups represents divine love and harmony. Your family is blessed.',
    keywords: ['harmony', 'love', 'family', 'bliss'],
    image: '🌈',
  },
  // Swords
  {
    id: 42,
    name: 'Ace of Swords',
    suit: 'swords',
    number: 1,
    meaning: 'Breakthrough, clarity, sharp mind, new ideas',
    reversedMeaning: 'Inner clarity, re-thinking an idea, clouded judgement',
    description: 'The Ace of Swords represents mental clarity and breakthrough. The truth is revealed.',
    keywords: ['clarity', 'breakthrough', 'truth', 'ideas'],
    image: '⚔️',
  },
  {
    id: 43,
    name: 'Two of Swords',
    suit: 'swords',
    number: 2,
    meaning: 'Difficult choices, indecision, stalemate, blocked emotions',
    reversedMeaning: 'Indecision, confusion, information overload',
    description: 'The Two of Swords represents difficult choices and indecision. You are at a crossroads.',
    keywords: ['choices', 'indecision', 'stalemate', 'balance'],
    image: '🤔',
  },
  {
    id: 44,
    name: 'Three of Swords',
    suit: 'swords',
    number: 3,
    meaning: 'Heartbreak, emotional pain, sorrow, grief, hurt',
    reversedMeaning: 'Negative self-talk, releasing pain, optimism, forgiveness',
    description: 'The Three of Swords represents heartbreak and sorrow. Pain is necessary for growth.',
    keywords: ['heartbreak', 'sorrow', 'grief', 'pain'],
    image: '💔',
  },
  {
    id: 45,
    name: 'Four of Swords',
    suit: 'swords',
    number: 4,
    meaning: 'Rest, relaxation, meditation, contemplation, recuperation',
    reversedMeaning: 'Exhaustion, burn-out, deep contemplation, stagnation',
    description: 'The Four of Swords represents rest and recuperation. Take time to recover.',
    keywords: ['rest', 'relaxation', 'meditation', 'recovery'],
    image: '😴',
  },
  {
    id: 46,
    name: 'Five of Swords',
    suit: 'swords',
    number: 5,
    meaning: 'Conflict, disagreements, competition, defeat, winning at all costs',
    reversedMeaning: 'Reconciliation, making amends, past resentment',
    description: 'The Five of Swords represents conflict and defeat. Not every battle is worth fighting.',
    keywords: ['conflict', 'defeat', 'competition', 'betrayal'],
    image: '😤',
  },
  {
    id: 47,
    name: 'Six of Swords',
    suit: 'swords',
    number: 6,
    meaning: 'Transition, change, rite of passage, releasing baggage',
    reversedMeaning: 'Personal transition, resistance, unfinished business',
    description: 'The Six of Swords represents transition and moving on. You are leaving troubled waters behind.',
    keywords: ['transition', 'change', 'moving on', 'passage'],
    image: '⛵',
  },
  {
    id: 48,
    name: 'Seven of Swords',
    suit: 'swords',
    number: 7,
    meaning: 'Betrayal, deception, getting away with something, stealth',
    reversedMeaning: 'Imposter syndrome, self-deceit, keeping secrets',
    description: 'The Seven of Swords represents deception and betrayal. Someone is not being honest.',
    keywords: ['deception', 'betrayal', 'stealth', 'strategy'],
    image: '🤫',
  },
  {
    id: 49,
    name: 'Eight of Swords',
    suit: 'swords',
    number: 8,
    meaning: 'Negative thoughts, self-imposed restriction, imprisonment, victim mentality',
    reversedMeaning: 'Self-limiting beliefs, inner critic, releasing negative thoughts',
    description: 'The Eight of Swords represents feeling trapped. The prison is of your own making.',
    keywords: ['restriction', 'trapped', 'victim', 'limitation'],
    image: '⛓️',
  },
  {
    id: 50,
    name: 'Nine of Swords',
    suit: 'swords',
    number: 9,
    meaning: 'Anxiety, worry, fear, depression, nightmares',
    reversedMeaning: 'Inner turmoil, deep-seated fears, secrets, releasing worry',
    description: 'The Nine of Swords represents anxiety and worry. Your fears are keeping you up at night.',
    keywords: ['anxiety', 'worry', 'fear', 'nightmares'],
    image: '😰',
  },
  {
    id: 51,
    name: 'Ten of Swords',
    suit: 'swords',
    number: 10,
    meaning: 'Painful endings, deep wounds, betrayal, loss, crisis',
    reversedMeaning: 'Recovery, regeneration, resisting an inevitable end',
    description: 'The Ten of Swords represents painful endings. The worst is over, now you can heal.',
    keywords: ['endings', 'pain', 'betrayal', 'crisis'],
    image: '🗡️',
  },
  // Pentacles
  {
    id: 52,
    name: 'Ace of Pentacles',
    suit: 'pentacles',
    number: 1,
    meaning: 'New financial opportunity, manifestation, abundance, stability',
    reversedMeaning: 'Lost opportunity, lack of planning, scarcity mindset',
    description: 'The Ace of Pentacles represents new financial opportunities. Prosperity is within reach.',
    keywords: ['opportunity', 'abundance', 'prosperity', 'stability'],
    image: '💰',
  },
  {
    id: 53,
    name: 'Two of Pentacles',
    suit: 'pentacles',
    number: 2,
    meaning: 'Multiple priorities, time management, prioritization, adaptability',
    reversedMeaning: 'Over-committed, disorganization, reprioritization',
    description: 'The Two of Pentacles represents juggling multiple priorities. Balance is key.',
    keywords: ['balance', 'priorities', 'adaptability', 'juggling'],
    image: '🤹',
  },
  {
    id: 54,
    name: 'Three of Pentacles',
    suit: 'pentacles',
    number: 3,
    meaning: 'Teamwork, collaboration, learning, implementation',
    reversedMeaning: 'Disharmony, misalignment, working alone',
    description: 'The Three of Pentacles represents teamwork and collaboration. Together you can achieve more.',
    keywords: ['teamwork', 'collaboration', 'learning', 'craft'],
    image: '👷',
  },
  {
    id: 55,
    name: 'Four of Pentacles',
    suit: 'pentacles',
    number: 4,
    meaning: 'Saving money, security, conservatism, scarcity, control',
    reversedMeaning: 'Over-spending, greed, self-protection',
    description: 'The Four of Pentacles represents security and control. You are holding on too tightly.',
    keywords: ['security', 'control', 'conservation', 'stability'],
    image: '🏦',
  },
  {
    id: 56,
    name: 'Five of Pentacles',
    suit: 'pentacles',
    number: 5,
    meaning: 'Financial loss, poverty, lack mindset, isolation, worry',
    reversedMeaning: 'Recovery from financial loss, spiritual poverty',
    description: 'The Five of Pentacles represents financial hardship. Help is available if you ask.',
    keywords: ['hardship', 'poverty', 'loss', 'isolation'],
    image: '❄️',
  },
  {
    id: 57,
    name: 'Six of Pentacles',
    suit: 'pentacles',
    number: 6,
    meaning: 'Giving, receiving, sharing wealth, generosity, charity',
    reversedMeaning: 'Self-care, unpaid debts, one-sided charity',
    description: 'The Six of Pentacles represents generosity and sharing. Give and you shall receive.',
    keywords: ['generosity', 'giving', 'receiving', 'charity'],
    image: '🎁',
  },
  {
    id: 58,
    name: 'Seven of Pentacles',
    suit: 'pentacles',
    number: 7,
    meaning: 'Long-term view, sustainable results, perseverance, investment',
    reversedMeaning: 'Lack of long-term vision, limited success, impatience',
    description: 'The Seven of Pentacles represents patience and long-term vision. Your efforts will pay off.',
    keywords: ['patience', 'investment', 'vision', 'perseverance'],
    image: '🌱',
  },
  {
    id: 59,
    name: 'Eight of Pentacles',
    suit: 'pentacles',
    number: 8,
    meaning: 'Apprenticeship, repetitive tasks, mastery, skill development',
    reversedMeaning: 'Self-development, perfectionism, misdirected activity',
    description: 'The Eight of Pentacles represents mastery through practice. Keep honing your skills.',
    keywords: ['mastery', 'skill', 'practice', 'dedication'],
    image: '🔨',
  },
  {
    id: 60,
    name: 'Nine of Pentacles',
    suit: 'pentacles',
    number: 9,
    meaning: 'Abundance, luxury, self-sufficiency, financial independence',
    reversedMeaning: 'Self-worth, over-investment in work, hustling',
    description: 'The Nine of Pentacles represents abundance and luxury. You have achieved financial independence.',
    keywords: ['abundance', 'luxury', 'independence', 'success'],
    image: '💎',
  },
  {
    id: 61,
    name: 'Ten of Pentacles',
    suit: 'pentacles',
    number: 10,
    meaning: 'Wealth, financial security, family, long-term success, contribution',
    reversedMeaning: 'The dark side of wealth, financial failure',
    description: 'The Ten of Pentacles represents wealth and family legacy. You have built something lasting.',
    keywords: ['wealth', 'family', 'legacy', 'security'],
    image: '🏰',
  },
]

export function getRandomCards(count: number = 3): TarotCard[] {
  const shuffled = [...tarotCards].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}

export function getCardById(id: number): TarotCard | undefined {
  return tarotCards.find((card) => card.id === id)
}
